### ISSUE TITLE
analyst user role doesn't have access to data tables

### ISSUE THREAD

**Issue by eayo** [texas-justice-initiative/jail-population-reports#1]
Analyst user role can't view/select from data tables

Need to check:
- [x] schema permissions
- [x] table permissions

**Comment by ayota** [comment]
the issue was when the tables are regenerated, the role was losing permissions

`ALTER DEFAULT PRIVILEGES IN SCHEMA {schema} GRANT SELECT ON TABLES TO {role};` needs to be run on every new schema created to maintain privileges
