### ISSUE TITLE
build page for raw data clearinghouse

### ISSUE THREAD

**Issue by EvaRuthM** [texas-justice-initiative/jail-population-reports#19]
We need to build a page for people to go to in order to download the raw jail data reports that we have collected from TCJS. Ideas for this page: 
- Call the page County Jail Data /county-jail-data for now
- use same "table" that is on our "interactive data tools" page 
- list each type of report separately (there are four) --> then allow people to select a year from a drop-down menu (this is how the bucket is organized) 
- and add a column for the number of total reports

**Comment by judan** [comment]
Design -- Dropdown? Sort by dates
